// src/core/reporter.js
'use strict';

const { SPDX_DATA } = require('../licenses/spdx-data');

const RISK_COLORS = {
  critical: '\x1b[91m',
  high: '\x1b[31m',
  medium: '\x1b[33m',
  low: '\x1b[32m',
  none: '\x1b[32m',
  unknown: '\x1b[90m',
};
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';

class Reporter {
  constructor(options = {}) {
    this.verbose = options.verbose || false;
    this.summaryOnly = options.summaryOnly || false;
    this.noColor = process.env.NO_COLOR || !process.stdout.isTTY;
  }

  c(code, text) {
    return this.noColor ? text : `${code}${text}${RESET}`;
  }

  /**
   * Plain text report for terminal output
   */
  text(report) {
    const lines = [];
    const { violations, warnings, packages, policy, meta } = report;

    lines.push('');
    lines.push(this.c(BOLD, '⚖️  License Compliance Report'));
    lines.push(this.c(DIM, `   ${new Date(report.timestamp).toLocaleString()}`));
    lines.push('');

    // Summary table
    lines.push(this.c(DIM, '  ──────────────────────────────────'));
    lines.push(`  📦 Total packages    : ${this.c(BOLD, packages.length)}`);
    lines.push(`  ✅ Compliant         : ${this.c(GREEN, packages.length - violations.length)}`);
    lines.push(`  ❌ Violations        : ${violations.length > 0 ? this.c(RED, violations.length) : this.c(GREEN, 0)}`);
    lines.push(`  ⚠️  Warnings          : ${warnings.length > 0 ? this.c(YELLOW, warnings.length) : this.c(GREEN, 0)}`);
    if (meta) {
      lines.push(`  🌍 Ecosystems        : ${this.c(CYAN, (meta.ecosystems || []).join(', '))}`);
      lines.push(`  ⏱  Duration          : ${meta.durationMs || 0}ms`);
    }
    lines.push(this.c(DIM, '  ──────────────────────────────────'));
    lines.push('');

    if (this.summaryOnly) {
      return lines.join('\n');
    }

    // Violations detail
    if (violations.length > 0) {
      lines.push(this.c(BOLD + RED, `  ❌ VIOLATIONS (${violations.length})`));
      lines.push('');

      for (const v of violations) {
        lines.push(this.c(BOLD, `  • ${v.name}@${v.version}`) + this.c(DIM, ` [${v.ecosystem}]`));
        lines.push(`    License : ${this.c(RED, v.license)}`);
        if (v.dependencyPath) {
          lines.push(this.c(DIM, `    Path    : ${v.dependencyPath}`));
        }
        for (const reason of v.violationReasons || []) {
          lines.push(this.c(RED, `    ✗ ${reason}`));
        }
        lines.push('');
      }
    }

    // Warnings
    if (warnings.length > 0) {
      lines.push(this.c(BOLD + YELLOW, `  ⚠️  WARNINGS (${warnings.length})`));
      lines.push('');
      for (const w of warnings) {
        lines.push(this.c(BOLD, `  • ${w.name}@${w.version}`) + this.c(DIM, ` [${w.ecosystem}]`));
        lines.push(`    License : ${this.c(YELLOW, w.license)}`);
        for (const reason of w.warningReasons || []) {
          lines.push(this.c(YELLOW, `    ⚠ ${reason}`));
        }
        lines.push('');
      }
    }

    // All packages (verbose)
    if (this.verbose && packages.length > 0) {
      lines.push(this.c(BOLD, '  ALL PACKAGES'));
      lines.push('');
      for (const pkg of packages) {
        const spdx = SPDX_DATA[pkg.license] || {};
        const status = pkg.violationReasons?.length ? this.c(RED, '✗') : pkg.warningReasons?.length ? this.c(YELLOW, '⚠') : this.c(GREEN, '✓');
        lines.push(`  ${status} ${pkg.name}@${pkg.version} ${this.c(DIM, `[${pkg.license || 'UNKNOWN'}]`)}`);
      }
      lines.push('');
    }

    if (violations.length === 0 && warnings.length === 0) {
      lines.push(this.c(GREEN + BOLD, '  ✅ All dependencies comply with the license policy.'));
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Text summary (one-liner for CI output)
   */
  textSummary(report) {
    const { violations, warnings, packages } = report;
    if (violations.length > 0) {
      return `❌ ${violations.length} violation(s) found in ${packages.length} packages`;
    }
    if (warnings.length > 0) {
      return `⚠️  ${warnings.length} warning(s) in ${packages.length} packages (no violations)`;
    }
    return `✅ All ${packages.length} packages are compliant`;
  }

  /**
   * Markdown report (for PR comments, GitHub wiki, etc.)
   */
  markdown(report) {
    const { violations, warnings, packages, meta } = report;
    const lines = [];
    const status = violations.length > 0 ? '❌ License Compliance **FAILED**' : '✅ License Compliance **PASSED**';

    lines.push(`## ⚖️ ${status}`);
    lines.push('');
    lines.push(`> Generated by [license-compliance-enforcer](https://github.com/your-org/license-compliance-enforcer) · ${new Date().toUTCString()}`);
    lines.push('');

    lines.push('### Summary');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Total packages | ${packages.length} |`);
    lines.push(`| ✅ Compliant | ${packages.length - violations.length} |`);
    lines.push(`| ❌ Violations | **${violations.length}** |`);
    lines.push(`| ⚠️ Warnings | ${warnings.length} |`);
    if (meta?.ecosystems) {
      lines.push(`| Ecosystems | ${meta.ecosystems.join(', ')} |`);
    }
    lines.push('');

    if (violations.length > 0) {
      lines.push('### ❌ Violations');
      lines.push('');
      lines.push('| Package | Version | License | Risk | Issue |');
      lines.push('|---------|---------|---------|------|-------|');
      for (const v of violations) {
        const spdx = SPDX_DATA[v.license] || {};
        lines.push(`| \`${v.name}\` | ${v.version} | \`${v.license}\` | ${spdx.risk || '?'} | ${(v.violationReasons || []).join('; ')} |`);
      }
      lines.push('');
      lines.push('> ⚠️ **This PR cannot be merged until all violations are resolved or have approved exceptions.**');
      lines.push('');
    }

    if (warnings.length > 0) {
      lines.push('### ⚠️ Warnings');
      lines.push('');
      lines.push('| Package | License | Warning |');
      lines.push('|---------|---------|---------|');
      for (const w of warnings) {
        lines.push(`| \`${w.name}@${w.version}\` | \`${w.license}\` | ${(w.warningReasons || []).join('; ')} |`);
      }
      lines.push('');
    }

    lines.push('<details>');
    lines.push('<summary>📋 All Packages</summary>');
    lines.push('');
    lines.push('| Package | Version | License | Type | Compliant |');
    lines.push('|---------|---------|---------|------|-----------|');
    for (const pkg of packages) {
      const spdx = SPDX_DATA[pkg.license] || {};
      const comp = pkg.violationReasons?.length ? '❌' : pkg.warningReasons?.length ? '⚠️' : '✅';
      lines.push(`| \`${pkg.name}\` | ${pkg.version} | \`${pkg.license || 'UNKNOWN'}\` | ${spdx.type || '?'} | ${comp} |`);
    }
    lines.push('');
    lines.push('</details>');

    return lines.join('\n');
  }

  /**
   * HTML report - full standalone document
   */
  html(report) {
    const { violations, warnings, packages, meta } = report;
    const statusClass = violations.length > 0 ? 'fail' : warnings.length > 0 ? 'warn' : 'pass';
    const statusText = violations.length > 0 ? '❌ FAILED' : warnings.length > 0 ? '⚠️ WARNINGS' : '✅ PASSED';

    const pkgRows = packages.map(pkg => {
      const spdx = SPDX_DATA[pkg.license] || {};
      const statusIcon = pkg.violationReasons?.length ? '❌' : pkg.warningReasons?.length ? '⚠️' : '✅';
      const rowClass = pkg.violationReasons?.length ? 'violation' : pkg.warningReasons?.length ? 'warning' : '';
      return `
        <tr class="${rowClass}">
          <td>${statusIcon}</td>
          <td><code>${pkg.name}</code></td>
          <td>${pkg.version || '-'}</td>
          <td><span class="license-badge">${pkg.license || 'UNKNOWN'}</span></td>
          <td>${spdx.type || '-'}</td>
          <td>${pkg.ecosystem || '-'}</td>
          <td>${pkg.direct ? 'Direct' : 'Transitive'}</td>
          <td>${(pkg.violationReasons || pkg.warningReasons || []).join('<br>')}</td>
        </tr>`;
    }).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>License Compliance Report</title>
  <style>
    :root { --green: #00aa55; --red: #cc2244; --yellow: #cc8800; --bg: #f8fafc; --card: #fff; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: var(--bg); color: #1a2a3a; line-height: 1.5; }
    .header { background: #0f172a; color: #fff; padding: 24px 40px; }
    .header h1 { font-size: 24px; font-weight: 700; }
    .header p { color: #94a3b8; margin-top: 4px; font-size: 14px; }
    .status { display: inline-block; padding: 4px 16px; border-radius: 999px; font-weight: 700; font-size: 14px; margin-top: 12px; }
    .status.pass { background: #dcfce7; color: var(--green); }
    .status.fail { background: #fee2e2; color: var(--red); }
    .status.warn { background: #fef9c3; color: var(--yellow); }
    .container { max-width: 1200px; margin: 0 auto; padding: 32px 40px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
    .stat { background: var(--card); border-radius: 12px; padding: 20px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
    .stat .label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: .06em; }
    .stat .value { font-size: 36px; font-weight: 800; margin-top: 4px; }
    .value.red { color: var(--red); } .value.green { color: var(--green); } .value.yellow { color: var(--yellow); }
    .card { background: var(--card); border-radius: 12px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); margin-bottom: 24px; overflow: hidden; }
    .card-header { padding: 16px 24px; border-bottom: 1px solid #f1f5f9; font-weight: 600; font-size: 15px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { padding: 10px 16px; background: #f8fafc; text-align: left; font-weight: 600; color: #475569; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
    td { padding: 10px 16px; border-bottom: 1px solid #f1f5f9; }
    tr.violation { background: #fff5f5; }
    tr.warning { background: #fffbeb; }
    code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 12px; }
    .license-badge { background: #e0f2fe; color: #0369a1; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-family: monospace; }
    .footer { text-align: center; padding: 24px; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <h1>⚖️ License Compliance Report</h1>
    <p>Generated by license-compliance-enforcer · ${new Date().toUTCString()}</p>
    <div class="status ${statusClass}">${statusText}</div>
  </div>
  <div class="container">
    <div class="stats">
      <div class="stat"><div class="label">Total Packages</div><div class="value">${packages.length}</div></div>
      <div class="stat"><div class="label">Violations</div><div class="value ${violations.length > 0 ? 'red' : 'green'}">${violations.length}</div></div>
      <div class="stat"><div class="label">Warnings</div><div class="value ${warnings.length > 0 ? 'yellow' : 'green'}">${warnings.length}</div></div>
      <div class="stat"><div class="label">Compliant</div><div class="value green">${packages.length - violations.length}</div></div>
    </div>
    <div class="card">
      <div class="card-header">📦 All Packages</div>
      <table>
        <thead><tr>
          <th>Status</th><th>Package</th><th>Version</th><th>License</th>
          <th>Type</th><th>Ecosystem</th><th>Dependency</th><th>Issues</th>
        </tr></thead>
        <tbody>${pkgRows}</tbody>
      </table>
    </div>
  </div>
  <div class="footer">Generated by <a href="https://github.com/your-org/license-compliance-enforcer">license-compliance-enforcer</a> · Free & Open Source · MIT License</div>
</body>
</html>`;
  }

  /**
   * JUnit XML for CI systems (Jenkins, CircleCI, etc.)
   */
  junit(report) {
    const { violations, packages } = report;
    const timestamp = new Date().toISOString();
    const testcases = packages.map(pkg => {
      const failed = pkg.violationReasons?.length > 0;
      if (failed) {
        return `    <testcase name="${pkg.name}@${pkg.version}" classname="${pkg.ecosystem}" time="0">
      <failure message="${(pkg.violationReasons || []).join('; ')}" type="LicenseViolation">${pkg.license}</failure>
    </testcase>`;
      }
      return `    <testcase name="${pkg.name}@${pkg.version}" classname="${pkg.ecosystem}" time="0"/>`;
    }).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="License Compliance" tests="${packages.length}" failures="${violations.length}" timestamp="${timestamp}">
${testcases}
  </testsuite>
</testsuites>`;
  }

  /**
   * SARIF 2.1.0 for GitHub Code Scanning
   * Spec: https://docs.oasis-open.org/sarif/sarif/v2.1.0/
   */
  sarif(report) {
    const { violations } = report;
    const results = violations.map(v => ({
      ruleId: `LCE-${(v.license || 'UNKNOWN').replace(/[^A-Z0-9]/gi, '-')}`,
      level: v.riskLevel === 'critical' ? 'error' : v.riskLevel === 'high' ? 'error' : 'warning',
      message: {
        text: `${v.name}@${v.version} uses ${v.license} which violates the license policy: ${(v.violationReasons || []).join('; ')}`,
      },
      locations: [{
        physicalLocation: {
          artifactLocation: { uri: v.manifestFile || 'package.json' },
          region: { startLine: 1 },
        },
      }],
      fingerprints: {
        'package/v1': `${v.ecosystem}:${v.name}@${v.version}`,
      },
    }));

    return {
      '$schema': 'https://json.schemastore.org/sarif-2.1.0.json',
      version: '2.1.0',
      runs: [{
        tool: {
          driver: {
            name: 'license-compliance-enforcer',
            version: require('../../package.json').version,
            informationUri: 'https://github.com/your-org/license-compliance-enforcer',
            rules: violations.map(v => ({
              id: `LCE-${(v.license || 'UNKNOWN').replace(/[^A-Z0-9]/gi, '-')}`,
              shortDescription: { text: `Disallowed license: ${v.license}` },
              fullDescription: { text: `Package ${v.name} uses ${v.license} which violates the project license policy.` },
              helpUri: 'https://github.com/your-org/license-compliance-enforcer/docs/licenses',
            })),
          },
        },
        results,
      }],
    };
  }
}

module.exports = Reporter;
